//Admin Login Actions
export const ADMIN_LOGIN_REQUEST= 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS= 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILURE= 'ADMIN_LOGIN_FAILURE';
//Client Login actions
export const LOGIN_REQUEST= 'LOGIN_REQUEST';
export const LOGIN_SUCCESS= 'LOGIN_SUCCESS';
export const LOGIN_FAILURE= 'LOGIN_FAILURE';
export const GET_NEW_TOKEN= 'GET_NEW_TOKEN';

export const GET_CLIENT_REQUEST = "GET_CLIENT_REQUEST";
export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS";
export const GET_CLIENT_FAILED = "GET_CLIENT_FAILED";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILED = "EDIT_PROFILE_FAILED";
//logout actions
export const LOGOUT= 'LOGOUT';

//Employees actions
export const GET_ALL_EMPLOYEE_REQUEST='GET_ALL_EMPLOYEE_REQUEST';
export const GET_ALL_EMPLOYEE_SUCCESS='GET_ALL_EMPLOYEE_SUCCESS';
export const GET_ALL_EMPLOYEE_FAILED='GET_ALL_EMPLOYEE_FAILED';

export const GET_EMPLOYEE_REQUEST='GET_EMPLOYEE_REQUEST';
export const GET_EMPLOYEE_SUCCESS='GET_EMPLOYEE_SUCCESS';
export const GET_EMPLOYEE_FAILED='GET_EMPLOYEE_FAILED';

export const EDIT_EMPLOYEE_REQUEST='EDIT_EMPLOYEE_REQUEST';
export const EDIT_EMPLOYEE_SUCCESS='EDIT_EMPLOYEE_SUCCESS';
export const EDIT_EMPLOYEE_FAILED='EDIT_EMPLOYEE_FAILED';
//Employee Selection
export const EMPLOYEE_SELECTED="EMPLOYEE_SELECTED";
export const DEPARTEMENT_SELECTED="DEPARTEMENT_SELECTED";

//Registeration actions
export const REGISTER_REQUEST= "REGISTER_REQUEST";
export const REGISTER_SUCCESS= 'REGISTER_SUCCESS';
export const REGISTER_FAILURE= 'REGISTER_FAILURE';

//Departement Action
export const GET_ALL_DEPARTEMENT_REQUEST = "GET_ALL_DEPARTEMENT_REQUEST";
export const GET_ALL_DEPARTEMENT_SUCCESS = "GET_ALL_DEPARTEMENT_SUCCESS";
export const GET_ALL_DEPARTEMENT_FAILURE = "GET_ALL_DEPARTEMENT_FAILURE";


//Create new Depatrment
export const ADD_DEAPARTEMENT_REQUEST = "ADD_DEPARTEMENT_REQUEST";
export const ADD_DEAPARTEMENT_SUCCESS = "ADD_DEPARTEMENT_SUCCESS";
export const ADD_DEAPARTEMENT_FAILURE = "ADD_DEPARTEMENT_FAILURE";

export const EDIT_DEAPARTEMENT_REQUEST = "EDIT_DEPARTEMENT_REQUEST";
export const EDIT_DEAPARTEMENT_SUCCESS = "EDIT_DEPARTEMENT_SUCCESS";
export const EDIT_DEAPARTEMENT_FAILURE = "EDIT_DEPARTEMENT_FAILURE";

//Create new Employee
export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_FAILURE";

//Delete Action
export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_FAILURE = "DELETE_EMPLOYEE_FAILURE";
export const DELETE_DEPARTEMENT_REQUEST = "DELETE_EMPLOYEE_REQUEST";
export const DELETE_DEPARTEMENT_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_DEPARTEMENT_FAILURE = "DELETE_EMPLOYEE_FAILURE";

//Companies Action 
export const GET_COMPANIES_REQUEST = "GET_COMPANIES_REQUEST";
export const GET_COMPANIES_SUCCESS = "GET_COMPANIES_SUCCESS";
export const GET_COMPANIES_FAILURE = "GET_COMPANIES_FAILURE";

export const GET_INPUT_REQUEST = "GET_INPUT_REQUEST";

//Activity Action
export const REPORT_ACTIVITY_REQUEST = "ACTION_ACTIVITY_REQUEST";
export const REPORT_ACTIVITY_SUCCESS = "ACTION_ACTIVITY_SUCCESS";
export const REPORT_ACTIVITY_FAILED = "ACTION_ACTIVITY_FAILED";